version: '3.7'

services:
  upscale_service:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
#    stdin_open: true
#    tty: true