version: '3.7'

services:
  upscale_service:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "${PORT}:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT}
              capabilities: [ gpu ]
#    stdin_open: true
#    tty: true

#  upscale_service2:
#    build:
#      context: .
#    container_name: ai2
#    ports:
#      - "12630:8000"
#      - "12639:22"
#    stdin_open: true
#    tty: true
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]