version: '3.7'

services:
  upscale_service:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "${PORT}:8000"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
#    stdin_open: true
#    tty: true