version: '3.7'

services:
  upscale_service:
    build:
      context: .
    container_name: ai
    ports:
      - "12530:8000"
      - "12539:22"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [ gpu ]

#  upscale_service2:
#    build:
#      context: .
#    container_name: ai2
#    ports:
#      - "12630:8000"
#      - "12639:22"
#    stdin_open: true
#    tty: true
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]